# NumPy

<img src="https://numpy.org/images/logos/numpy.svg" alt="NumPy" style="width: 100px;"/><br>

The fundamental package for scientific computing with Python. Use for basic data representation and linear algebra operation. NumPy also provide several data formats and array format for python. The data manipulation and data preprocessing also can be done with NumPy. From Aj.Ple experience, Aj.Ple suggest to change data representation to NumPy for Data Engineering & Data Analytics work. <br>

P.S. Linear Algebra is about linear equation in form of vector and matrix !!

www.numpy.org

### 1. NumPy Array

To use external Library in PyThon, we will use the command called <i>import</i>.<br> In this example, we use external library called <i>NumPy</i> and give it a short name as <i>np</i>. 

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a[0]

1

In [4]:
a[2:5]

array([3, 4, 5])

In [5]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [6]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
a[-1] # a(0)คือ index 0 ดังนั้น -1 มันจะไปนับตัวสุดท้ายใหม่วนไปเรื่อยๆ

10

In [8]:
a[-5:] # -5 คือ ถอยจาก 10 มา 5 ตัวเเต่มี : ดังนั้นะนับตั้งแต่ 6 ไป5 ตัว

array([ 6,  7,  8,  9, 10])

In [9]:
a[-5:-1]

array([6, 7, 8, 9])

In [10]:
np.size(a)

10

In [11]:
np.shape(a) #คำว่า shape ใน NumPy หมายถึงการให้ข้อมูลว่า array นั้นมีสมาชิกกี่ตัว กี่แถว กี่คอลัมน์ กี่ตาราง

(10,)

In [12]:
a = a.reshape(1,10)
np.shape(a)

(1, 10)

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[0,0] # แถว , index

1

In [15]:
a[1,:] # เรียกแถวที่ 1 ออกมาทั้งหมด (จะนับจาก index 0 เสอมอย่าลืม!!) เเละ semicolon หมายถึงเอาหมด

array([4, 5, 6])

In [16]:
a[:,-1]

array([3, 6, 9])

In [17]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [18]:
a[0:2,:] = 0
a

array([[0, 0, 0],
       [0, 0, 0],
       [7, 8, 0]])

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0) # 0 = กว้าง ,1 = ยาว ,2 = สูง

4

In [20]:
np.size(a,0)

4

In [21]:
np.ndim(a) # 2 มิติ

2

### Data is Matrix.
So, Matrix management == Data Management <br>
rows    = samples <br>
columns = attributes, features

In [22]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [23]:
np.array(np_mix_matrix[:,1], dtype = int) # เรียกต้องมี type ด้วย

array([2, 4, 6])

### 2. Special Type of Matrix

In [24]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [25]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [26]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [27]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [28]:
c*d

array([[8., 0.],
       [0., 8.]])

In [29]:
np.matmul(c,d)

array([[8., 8.],
       [8., 8.]])

In [30]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [31]:
np.sqrt(np.full((2,2),4)) #รากที่ 2 ของสี่

array([[2., 2.],
       [2., 2.]])

In [32]:

np.empty([5,5])

array([[4.68445407e-310, 2.15041615e-259, 6.01347002e-154,
        5.04533094e+223, 2.85776196e+227],
       [1.95124604e-153, 6.46572285e+170, 1.45517163e-152,
        3.55050335e+180, 6.96409365e+252],
       [2.46052274e-154, 6.01347002e-154, 5.37625007e+241,
        6.25907157e-085, 6.01347002e-154],
       [7.49912311e+247, 6.01347002e-154, 1.42731838e+228,
        3.81187285e+180, 6.99177862e+228],
       [4.83784345e+276, 2.51970211e+180, 1.17549700e+214,
        6.01347002e-154, 2.08725699e+214]])

### 3. Random

In [33]:
np.random.rand()

0.9057334987531495

In [34]:
[np.random.randint(5) for i in range(10)] #ran INT สุ่มเลข จน. เต็ม

[0, 1, 1, 4, 2, 0, 2, 3, 1, 2]

In [35]:
np.seed = 1
np.random.randint(2,5)

4

In [36]:
np.random.rand(5,5)

array([[0.15999744, 0.274028  , 0.49657224, 0.58916803, 0.89947235],
       [0.62103629, 0.19339687, 0.15824867, 0.13933545, 0.90117314],
       [0.84866261, 0.25643963, 0.04699191, 0.81156831, 0.16374923],
       [0.25055333, 0.83373736, 0.1995791 , 0.03334156, 0.85659115],
       [0.84009655, 0.13352983, 0.25087449, 0.62837761, 0.78767613]])

In [37]:
np.round(np.random.rand(5,5))

array([[0., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 1.]])

In [38]:
# Ex 1. Please use random to generate this output
# ...


In [39]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([4, 4, 8, 6, 7])

In [40]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([ 7,  6, 10,  4,  2])

In [41]:
np_matrix = np.random.rand(5,5) # มีข้อมูล 5 row 5 colum
idx_choose = np.random.choice(5,3) # เลือก 3 แถว จาก 5 แถว ซึ่งจะเป็น 3แถวที่ถูกเลือก
np_matrix_choose = np_matrix[idx_choose,:] # 3 แถวที่ถูกเลือก
np_matrix_choose

array([[0.50633705, 0.07329565, 0.57299934, 0.48877928, 0.4972622 ],
       [0.08914852, 0.38302053, 0.44922828, 0.87896987, 0.10057128],
       [0.00465088, 0.93377755, 0.42711168, 0.7085017 , 0.90263719]])

In [42]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#
Ex_matrix = np.random.rand(10,5) 
Ex_matrix[:,4] = np.round(np.random.rand(1,10))
Ex_matrix

array([[0.4127511 , 0.05886837, 0.90054848, 0.71306579, 0.        ],
       [0.26100451, 0.45978585, 0.35607802, 0.80157568, 0.        ],
       [0.3723835 , 0.89664344, 0.39164271, 0.83864909, 0.        ],
       [0.76909817, 0.56683727, 0.83001596, 0.11466595, 1.        ],
       [0.80444512, 0.93330755, 0.5659602 , 0.47405448, 0.        ],
       [0.50765078, 0.73455739, 0.70364119, 0.83489772, 1.        ],
       [0.86025117, 0.31742844, 0.22751428, 0.61019338, 0.        ],
       [0.66670645, 0.17745859, 0.94069124, 0.88777532, 0.        ],
       [0.12101678, 0.32153213, 0.74902767, 0.33654869, 1.        ],
       [0.85100538, 0.63033636, 0.14012807, 0.10971533, 0.        ]])

In [43]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 6,  5,  6,  7,  1],
       [ 2,  1,  5,  1,  7],
       [ 6, 10,  2,  8,  2],
       [ 9,  2,  3,  3,  2],
       [ 5,  1, 10,  6,  4]])

In [86]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 0, 2, 1, 0],
       [2, 1, 1, 0, 2],
       [2, 0, 1, 2, 0],
       [2, 2, 1, 2, 2],
       [2, 1, 0, 2, 0]])

In [45]:
i,j = np.where(np_matrix == 2)

In [46]:
i

array([0, 0, 1, 1, 2, 3, 3, 3, 4])

In [47]:
j

array([0, 2, 0, 2, 3, 0, 1, 4, 1])

In [87]:
#Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[np.size(idx)-1,:] # beacuse no index 5 in this data

array([2, 1, 0, 2, 0])

In [88]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[0, 0, 2, 1, 0],
       [2, 2, 1, 2, 2],
       [2, 1, 0, 2, 0]])

In [50]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[1, 5, 7, 0, 2],
       [0, 1, 0, 4, 3],
       [4, 3, 5, 8, 5],
       [9, 1, 3, 4, 6],
       [3, 7, 3, 5, 4]])

In [89]:
result = (np_matrix == 2)
result

array([[False, False,  True, False, False],
       [ True,  True, False,  True,  True],
       [ True, False, False,  True, False]])

In [94]:
np_matrix[result] = 404
np_matrix # where == 2 that will change to 99

array([[  0,   0, 404,   1,   0],
       [404, 404,   1, 404, 404],
       [404,   1,   0, 404,   0]])

In [53]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

data_matrix

In [54]:
ten_matrix = np.random.randint(10,size = (10,5))
ten_matrix

array([[6, 4, 8, 2, 3],
       [6, 1, 0, 7, 5],
       [0, 8, 5, 3, 6],
       [1, 4, 2, 5, 0],
       [7, 5, 8, 8, 3],
       [7, 8, 6, 9, 4],
       [9, 4, 8, 8, 1],
       [9, 0, 3, 4, 5],
       [8, 2, 1, 4, 0],
       [0, 2, 3, 8, 2]])

label_vector

In [55]:
vector = np.random.randint(2,size = 10)
vector

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 0])

train_data

In [56]:
ten_matrix[np.where(vector == 0)]

array([[1, 4, 2, 5, 0],
       [7, 8, 6, 9, 4],
       [9, 4, 8, 8, 1],
       [8, 2, 1, 4, 0],
       [0, 2, 3, 8, 2]])

test_data

In [57]:
ten_matrix[np.where(vector == 1)]

array([[6, 4, 8, 2, 3],
       [6, 1, 0, 7, 5],
       [0, 8, 5, 3, 6],
       [7, 5, 8, 8, 3],
       [9, 0, 3, 4, 5]])

In [58]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[1, 4, 4, 3, 3],
       [5, 4, 3, 4, 4],
       [3, 5, 1, 2, 5],
       [4, 3, 1, 4, 5],
       [4, 3, 1, 2, 5]])

### 4. Important Function

In [59]:
rng = np.random.RandomState(0)
data = rng.randint(10,size = (5,5))
data

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [60]:
np.max(data)  #แปลงข้อมูลเป็น numpy array [np.array] เพื่อให้ไม่เกิด err ตอนเรียก np. function

9

In [61]:
np.max(data,0) # max ของแต่ละคอมลัมม์

array([9, 9, 8, 9, 7])

In [62]:
np.max(data,1) # max ของแต่ละแถว

array([7, 9, 8, 8, 9])

In [63]:
np.sum(data,0) # รวมของแต่ละ colum

array([32, 25, 31, 30, 17])

In [64]:
np.average(data)

5.4

In [65]:
data[0,:]

array([5, 0, 3, 3, 7])

In [66]:
np.argmax(data[0,:]) # ข้อมูลตำแหน่งที่ 4 สูงสุด ของ array data

4

In [67]:
np.argmin(data[0,:])

1

In [68]:
np.sort(data[0,:])

array([0, 3, 3, 5, 7])

In [69]:
np.argsort(data[0,:])

array([1, 2, 3, 0, 4])

In [70]:
#Ex.5 How to sort in decreasing order using np.sort
np.argsort(-data[0,:])

array([4, 0, 2, 3, 1])

In [71]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [72]:
np.linspace(5,10,10) # เอามาสับ จากค่า5ถึง10 มา 10 ค่าห่างแบบเท่าๆกัน

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [73]:
data = np.round(np.random.random((5,5))*3)
data

array([[3., 2., 2., 2., 1.],
       [1., 1., 1., 1., 2.],
       [1., 3., 2., 2., 3.],
       [2., 0., 1., 1., 1.],
       [1., 1., 2., 2., 2.]])

In [74]:
data.shape # ขนาดเท่าไหร่ * เท่าไหร่

(5, 5)

In [75]:
data.reshape(1,25) # ย่อยเป็น 1*25 ได้

array([[3., 2., 2., 2., 1., 1., 1., 1., 1., 2., 1., 3., 2., 2., 3., 2.,
        0., 1., 1., 1., 1., 1., 2., 2., 2.]])

In [76]:
tile = [[1,2],
        [3,4]]
tile

[[1, 2], [3, 4]]

In [77]:
np.tile(tile,(2,2)) # เอามาต่อกันให้เป็นขนาดตามที่เรากำหนด

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [78]:
#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
#

In [80]:
# Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [81]:
np.vstack( (data,data) ) #เอา matrix มาต่อ martrix จะต่อกี่อันก็ได้

array([[3., 2., 2., 2., 1.],
       [1., 1., 1., 1., 2.],
       [1., 3., 2., 2., 3.],
       [2., 0., 1., 1., 1.],
       [1., 1., 2., 2., 2.],
       [3., 2., 2., 2., 1.],
       [1., 1., 1., 1., 2.],
       [1., 3., 2., 2., 3.],
       [2., 0., 1., 1., 1.],
       [1., 1., 2., 2., 2.]])

In [82]:
np.hstack( (data,data) ) # เอามาต่อข้าง จะต่อกี่อันก็ได้

array([[3., 2., 2., 2., 1., 3., 2., 2., 2., 1.],
       [1., 1., 1., 1., 2., 1., 1., 1., 1., 2.],
       [1., 3., 2., 2., 3., 1., 3., 2., 2., 3.],
       [2., 0., 1., 1., 1., 2., 0., 1., 1., 1.],
       [1., 1., 2., 2., 2., 1., 1., 2., 2., 2.]])