# NumPy

<img src="https://numpy.org/images/logos/numpy.svg" alt="NumPy" style="width: 100px;"/><br>

The fundamental package for scientific computing with Python. Use for basic data representation and linear algebra operation. NumPy also provide several data formats and array format for python. The data manipulation and data preprocessing also can be done with NumPy. From Aj.Ple experience, Aj.Ple suggest to change data representation to NumPy for Data Engineering & Data Analytics work. <br>

P.S. Linear Algebra is about linear equation in form of vector and matrix !!

www.numpy.org

### 1. NumPy Array

To use external Library in PyThon, we will use the command called <i>import</i>.<br> In this example, we use external library called <i>NumPy</i> and give it a short name as <i>np</i>. 

In [3]:
import numpy as np

In [55]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a[0]

1

In [6]:
a[2:5]

array([3, 4, 5])

In [7]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [8]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [51]:
a[-1] # a(0)คือ index 0 ดังนั้น -1 มันจะไปนับตัวสุดท้ายใหม่วนไปเรื่อยๆ

6

In [10]:
a[-5:] # -5 คือ ถอยจาก 10 มา 5 ตัวเเต่มี : ดังนั้นะนับตั้งแต่ 6 ไป5 ตัว

array([ 6,  7,  8,  9, 10])

In [11]:
a[-5:-1]

array([6, 7, 8, 9])

In [56]:
np.size(a)

10

In [57]:
np.shape(a) #คำว่า shape ใน NumPy หมายถึงการให้ข้อมูลว่า array นั้นมีสมาชิกกี่ตัว กี่แถว กี่คอลัมน์ กี่ตาราง

(10,)

In [58]:
a = a.reshape(1,10)
np.shape(a)

(1, 10)

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a[0,0] # แถว , index

1

In [16]:
a[1,:] # เรียกแถวที่ 1 ออกมาทั้งหมด (จะนับจาก index 0 เสอมอย่าลืม!!) เเละ semicolon หมายถึงเอาหมด

array([4, 5, 6])

In [17]:
a[:,-1]

array([3, 6, 9])

In [18]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [80]:
a[0:2,:] = 0
a

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0) # 0 = กว้าง ,1 = ยาว ,2 = สูง

4

In [69]:
np.size(a,0)

4

In [59]:
np.ndim(a) # 2 มิติ

2

### Data is Matrix.
So, Matrix management == Data Management <br>
rows    = samples <br>
columns = attributes, features

In [22]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [84]:
np.array(np_mix_matrix[:,1], dtype = int) # เรียกต้องมี type ด้วย

array([2, 4, 6])

### 2. Special Type of Matrix

In [24]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [25]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [26]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [27]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [28]:
c*d

array([[8., 0.],
       [0., 8.]])

In [85]:
np.matmul(c,d)

array([[8., 8.],
       [8., 8.]])

In [29]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [30]:
np.sqrt(np.full((2,2),4)) #รากที่ 2 ของสี่

array([[2., 2.],
       [2., 2.]])

In [31]:

np.empty([5,5])

array([[4.66586942e-310, 8.15208316e-322, 9.29654051e+242,
        4.39324667e+228, 5.37988202e+228],
       [1.38795503e+219, 2.86749934e+161, 5.95144714e+228,
        1.99886516e+161, 1.09313427e+189],
       [3.31602997e-080, 2.16063140e+233, 8.48254144e+175,
        2.99688141e-080, 1.43769634e-023],
       [3.23225296e-295, 1.24571164e+137, 6.51686540e+256,
        9.98390183e+164, 3.89570063e+034],
       [7.38255668e+015, 6.46676985e+256, 5.03211681e-071,
        3.28175647e-028, 5.05060978e+223]])

### 3. Random

In [32]:
np.random.rand()

0.3601029149602025

In [98]:
[np.random.randint(5) for i in range(10)] #ran INT สุ่มเลข จน. เต็ม

[4, 2, 3, 1, 3, 0, 0, 0, 3, 3]

In [115]:
np.seed = 1
np.random.randint(2,5)

2

In [35]:
np.random.rand(5,5)

array([[0.23111102, 0.6048542 , 0.23960384, 0.66506221, 0.6866294 ],
       [0.04367903, 0.14832278, 0.86726972, 0.85499102, 0.86743112],
       [0.81522519, 0.03597781, 0.33065744, 0.21812165, 0.16519211],
       [0.34158537, 0.68755043, 0.18063211, 0.87248315, 0.07641252],
       [0.66428134, 0.31285578, 0.99199348, 0.40158997, 0.60029165]])

In [36]:
np.round(np.random.rand(5,5))

array([[1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 1.]])

In [37]:
# Ex 1. Please use random to generate this output
# ...


In [38]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([10,  8,  4, 10,  9])

In [39]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([ 2,  9,  5, 10,  3])

In [40]:
np_matrix = np.random.rand(5,5) # มีข้อมูล 5 row 5 colum
idx_choose = np.random.choice(5,3) # เลือก 3 แถว จาก 5 แถว ซึ่งจะเป็น 3แถวที่ถูกเลือก
np_matrix_choose = np_matrix[idx_choose,:] # 3 แถวที่ถูกเลือก
np_matrix_choose

array([[0.4151426 , 0.4372073 , 0.95194044, 0.39754661, 0.85567957],
       [0.26792807, 0.43049826, 0.69950872, 0.64861609, 0.91518845],
       [0.22047971, 0.87937792, 0.08215828, 0.40142468, 0.82234648]])

In [170]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#
Ex_matrix = np.random.rand(18,5)
Ex_matrix[17,:] = np.round(np.random.rand(1,5)) # 1 dimension 5 colum
Ex_matrix

array([[0.64810503, 0.87511804, 0.79052051, 0.14110759, 0.54558212],
       [0.10559155, 0.04529464, 0.65638586, 0.53515233, 0.08202369],
       [0.03493925, 0.98975641, 0.03002133, 0.44452825, 0.50461902],
       [0.11728015, 0.16906178, 0.35180501, 0.76167588, 0.50708242],
       [0.63790187, 0.98517456, 0.76800544, 0.4343615 , 0.44644192],
       [0.61877208, 0.66536521, 0.50071093, 0.64486122, 0.02353249],
       [0.42962286, 0.27893808, 0.12917445, 0.09954651, 0.60319217],
       [0.52360055, 0.25358412, 0.47095006, 0.49223232, 0.19500898],
       [0.65209306, 0.78091936, 0.79146354, 0.60246983, 0.51163858],
       [0.06100714, 0.2878313 , 0.09327145, 0.96382316, 0.13508015],
       [0.15177541, 0.88957662, 0.94392828, 0.76582904, 0.00540492],
       [0.00134627, 0.37810077, 0.14339537, 0.01838614, 0.46406669],
       [0.9430619 , 0.32381957, 0.66114068, 0.65223535, 0.2510801 ],
       [0.65042525, 0.21233397, 0.12200741, 0.70138329, 0.11344082],
       [0.99690922, 0.1834524 , 0.

In [42]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 0,  6,  4,  4,  3],
       [ 1,  0,  4,  5,  8],
       [ 7,  3,  4,  3,  8],
       [ 5,  3,  3, 10,  4],
       [ 4, 10,  7,  8,  9]])

In [263]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 0, 0, 0, 2],
       [1, 0, 0, 0, 0],
       [1, 2, 1, 0, 1],
       [0, 2, 2, 2, 0],
       [1, 2, 0, 0, 1]])

In [265]:
i,j = np.where(np_matrix == 2)

In [266]:
i

array([0, 2, 3, 3, 3, 4])

In [269]:
j

array([4, 1, 1, 2, 3, 1])

In [192]:
#Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[np.size(idx)-1,:] # beacuse no index 5 in this data

array([ 3, 99,  4,  8,  5])

In [177]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 1, 1, 1, 0],
       [2, 0, 2, 2, 0],
       [0, 2, 1, 2, 2]])

In [181]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[5, 0, 6, 6, 0],
       [8, 5, 1, 4, 3],
       [6, 7, 0, 4, 2],
       [0, 2, 5, 6, 7],
       [3, 2, 4, 8, 5]])

In [182]:
result = (np_matrix == 2)
result

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False,  True, False, False, False],
       [False,  True, False, False, False]])

In [183]:
np_matrix[result] = 99
np_matrix # where == 2 that will change to 99

array([[ 5,  0,  6,  6,  0],
       [ 8,  5,  1,  4,  3],
       [ 6,  7,  0,  4, 99],
       [ 0, 99,  5,  6,  7],
       [ 3, 99,  4,  8,  5]])

In [ ]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

data_matrix

In [274]:
ten_matrix = np.random.randint(10,size = (10,5))
ten_matrix

array([[2, 0, 1, 7, 6],
       [1, 1, 8, 5, 4],
       [9, 5, 8, 6, 9],
       [9, 8, 3, 1, 7],
       [3, 8, 3, 7, 8],
       [8, 9, 3, 0, 2],
       [8, 3, 4, 6, 4],
       [3, 1, 1, 3, 9],
       [9, 8, 7, 2, 8],
       [4, 2, 4, 9, 3]])

label_vector

In [275]:
vector = np.random.randint(2,size = 10)
vector

array([1, 0, 1, 0, 1, 1, 1, 0, 1, 0])

train_data

In [288]:
ten_matrix[np.where(vector == 0)]

array([[1, 1, 8, 5, 4],
       [9, 8, 3, 1, 7],
       [3, 1, 1, 3, 9],
       [4, 2, 4, 9, 3]])

test_data

In [287]:
ten_matrix[np.where(vector == 1)]

array([[2, 0, 1, 7, 6],
       [9, 5, 8, 6, 9],
       [3, 8, 3, 7, 8],
       [8, 9, 3, 0, 2],
       [8, 3, 4, 6, 4],
       [9, 8, 7, 2, 8]])

In [ ]:
data = np.random.randint(5,size=(5,5)) + 1
data

### 4. Important Function

In [ ]:
np.max(data)

In [ ]:
np.max(data,0)

In [ ]:
np.max(data,1)

In [ ]:
np.sum(data)

In [ ]:
np.average(data)

In [ ]:
data[0,:]

In [ ]:
np.argmax(data[0,:])

In [ ]:
np.argmin(data[0,:])

In [ ]:
np.sort(data[0,:])

In [ ]:
np.argsort(data[0,:])

In [ ]:
#Ex.5 How to sort in decreasing order using np.sort
#

In [ ]:
np.arange(1,10,2)

In [ ]:
np.linspace(5,10,10)

In [ ]:
data = np.round(np.random.random((5,5))*3)
data

In [ ]:
data.shape

In [ ]:
data.reshape(1,25)

In [ ]:
tile = [[1,2],
        [3,4]]
tile

In [ ]:
np.tile(tile,(4,1))

In [ ]:
#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

In [ ]:
#

In [ ]:
# Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test